GET FILE="/Users/kwcity.hk/my-git/hkupop-legco/hkupop_0730_start_and_all/LC2016_final_current_v1_POP.sav".

WEIGHT by weight.	
	
CROSSTABS
	/TABLES= date BY	 R2 R3 R4 R5 R6 R8 R10		
	/FORMAT=AVALUE TABLES PIVOT
	/STATISTICS=CHISQ 	
    /CELLS=COUNT ROW COLUMN TOTAL
    
WEIGHT BY weight.

CROSSTABS
	/TABLES= R10	BY	 R2
	/FORMAT=AVALUE TABLES PIVOT
	/STATISTICS=CHISQ
	/CELLS=COUNT ROW COLUMN TOTAL.
